### ISSUE TITLE
TODO: termine correction du texte public2018-D2

### ISSUE THREAD

**Issue by Naereen** [Naereen/notebooks#9]
Pour l'instant : https://github.com/Naereen/notebooks/blob/master/agreg/public2018_D2.ipynb

- [ ] Mieux comprendre ces opérateurs oplus et omul
- [ ] Voir pour implémenter un "bonus" aussi
- [ ] Ou une visualisation sympa ?

**Comment by Naereen** [comment]
> Je n'aurai jamais le temps d'implémenter des bonus, et la correction est déjà suffisante, je ferme ça.
